# Generated by Django 4.2 on 2025-04-01 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_moodcause_recommendation_recommendationcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('reminder_type', models.CharField(choices=[('streak', 'Streak Reminder'), ('regular', 'Regular Reminder')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='journalreminder',
            index=models.Index(fields=['user', 'sent_at'], name='core_journa_user_id_3f30a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalreminder',
            unique_together={('user', 'sent_at')},
        ),
    ]
