# Generated by Django 4.2 on 2025-02-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_moodlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='emotions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
