# Generated by Django 4.2 on 2025-02-27 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_moodlog_journal_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
