# Generated by Django 4.2 on 2025-02-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_journalentry_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'date'], name='core_journa_user_id_6b05b4_idx'),
        ),
    ]
