# Generated by Django 4.2 on 2025-02-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_journalentry_core_journa_user_id_6b05b4_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('user', 'date')},
        ),
    ]
