# Generated by Django 4.2 on 2025-02-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_journalentry_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together=set(),
        ),
    ]
